# change the followings to match your Github username and repo name
baseurl: "/blog" # the name of your github repo
url: "https://kayvane1.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "About Kayvane"
description: A blog for code walkthroughs and tutorials. Focused on ML projects, ML Ops, deployments & methodologies

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Kayvane Shakerifar
author-bio: Nerd | ML Enthusiast | ML Product Manager  # change to false to hide
author-image: profile.jpg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: CV
  permalink: cv
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: https://github.com/kayvane1
linkedin: https://linkedin.com/in/kayvane
medium: https://medium.com/@kayvane.shakerifar
google-scholar: false
email: kayvane.shakerifar@gmail.com

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/kayvane1

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
